# Generated by Django 4.2.14 on 2024-08-07 12:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_remove_friend_friends_alter_friend_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='friends',
        ),
        migrations.AddField(
            model_name='friend',
            name='friends',
            field=models.ManyToManyField(related_name='friends_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
