# Generated by Django 4.2.14 on 2024-07-31 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expense', '0002_expensedb_delete_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensedb',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
