# Generated by Django 4.2.14 on 2024-08-02 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_friendsgroup_creator'),
        ('expense', '0006_expensedb_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensesplit',
            name='group_num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.friendsgroup'),
        ),
    ]
