# Generated by Django 4.2.14 on 2024-08-02 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_friendsgroup_creator'),
        ('expense', '0007_expensesplit_group_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensedb',
            name='group',
        ),
        migrations.AddField(
            model_name='expensedb',
            name='group_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.friendsgroup'),
        ),
    ]
