# Generated by Django 4.2.14 on 2024-08-06 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0008_remove_expensedb_group_expensedb_group_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensesplit',
            old_name='group_num',
            new_name='group_name',
        ),
    ]
